version: '3.8'

services:
  whoami:
    image: jwilder/whoami
    ports:
      - 8000:8000

# version: '3.8'

# services:
#   backend:
#     image:
#     environment:
#       - VARIABLE=VALUE
#       - VARIABLE2=VALUE2